# Check https://circleci.com/docs/2.0/language-javascript/ for more details

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8.5.0

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: yarn

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  deploy:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .

      - deploy:
          name: Deploy
          command: |
            git config --global user.name "Circle CI"
            git config --global user.email ${GIT_USER_EMAIL}
            yarn run update
            yarn build
            yarn deploy

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
